spring:
  application:
    name: Diddycart

  docker:
    compose:
      enabled: false

  datasource:
    url: jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:5432/postgres?user=postgres.sihigvbstpqzhvgeknkr&password=T3acedge#2011
    username: postgres.sihigvbstpqzhvgeknkr
    password: T3acedge#2011
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 15
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 1800000

  # JPA Settings
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        "[format_sql]": true

diddycart:
  app:
    jwtSecret: SagarKePullKeNicheTeriMaaBhajiaTaleMeraBaapKhaKeChale
    jwtExpirationMs: 86400000
